- name: Add Jenkins repository
  block:
    - name: Add key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Add repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo


- name: Install Jenkins
  dnf:
    name: jenkins
    state: present
    update_cache: true