---
- hosts: jenkins_agents
  gather_facts: yes
  become: yes
  roles:
    - create_agent_jenkins_user
    - copy_hosts
    - setup_jenkins_ssh
    - install_git
    - install_java
    - install_jenkins